//! Golden-image tests for the edit pipeline.
//!
//! The unit tests in `edit.rs` assert properties — involutions cancel, a mirror
//! reflects, the predicted size matches what `apply` produces — and properties have
//! a blind spot that matters here: **they do not see direction**. If `FlipHorizontal`
//! were wired to `flip_vertical`, flipping twice would still return the original and
//! the size would still be unchanged, so every existing test would pass. The same
//! goes for the two rotations: four quarter turns come back to the start whichever
//! way they go round.
//!
//! So these compare whole images against stored ones. That pins everything nobody
//! thought to assert — the exact rounding in an adjustment, the alpha in the canvas
//! a mirror allocates, which pixel a crop starts at — and it is what a refactor of
//! the pipeline has to survive.
//!
//! **A golden generated by the code it tests proves nothing on the day it is
//! written.** It only catches what changes afterwards. So each case also states, as
//! an assertion against the *stored file*, where a marker pixel unique to the
//! fixture has ended up — and that is the half that says which way round the stored
//! image is, independently of whatever produced it.
//!
//! **Seen to fail, on purpose.** `Op::apply` was edited to swap `FlipHorizontal`
//! with `FlipVertical` and `RotateCw` with `RotateCcw`, and the result was the whole
//! point of this file: all 26 property tests in `edit.rs` still passed, and five
//! cases here failed. A verification nobody has watched fail is not a verification.
//!
//! Regenerating: `IMAGINER_BLESS=1 cargo test -p imaginer-core --test golden`.
//! Look at what changes before committing it. A golden accepted without being
//! looked at is a test that has been switched off.

use std::path::{Path, PathBuf};

use imaginer_core::image::{self, Rgba, RgbaImage};
use imaginer_core::{Adjust, Edits, Op};

/// Fixture size. Small enough that the stored PNGs are a few hundred bytes and can
/// be opened and understood, large enough to be asymmetric in both axes.
const WIDTH: u32 = 8;
const HEIGHT: u32 = 6;

/// The one pixel that appears exactly once in the fixture. Where it lands is what
/// says which way an op turned things.
const MARKER: Rgba<u8> = Rgba([255, 255, 255, 255]);

/// The image every case starts from.
///
/// Generated rather than committed: it is the *outputs* that need to be looked at
/// by a human, and a source image in the repo would be one more thing that could
/// drift from the code describing it. Asymmetric on both axes, with alpha varying
/// down the image so that a mirror's fresh canvas and a crop's copy are exercised
/// on something other than fully opaque pixels.
fn fixture() -> RgbaImage {
    RgbaImage::from_fn(WIDTH, HEIGHT, |x, y| {
        if (x, y) == (0, 0) {
            return MARKER;
        }
        Rgba([
            (20 + x * 28) as u8,
            (30 + y * 36) as u8,
            (200 - x * 9 - y * 7) as u8,
            (255 - y * 20) as u8,
        ])
    })
}

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("golden")
}

fn blessing() -> bool {
    std::env::var_os("IMAGINER_BLESS").is_some_and(|value| value != "0")
}

/// Compare `actual` against the stored image of that name, or write it if blessing.
///
/// Pixels are compared, not file bytes. A PNG encoder is free to change how it
/// deflates between releases, and a test that failed because the compression
/// improved would teach everyone to bless without looking.
fn assert_matches_golden(name: &str, actual: &RgbaImage) {
    let path = golden_dir().join(format!("{name}.png"));

    if blessing() {
        std::fs::create_dir_all(golden_dir()).expect("the golden directory is writable");
        actual.save(&path).expect("failed to write the golden");
        println!("blessed {}", path.display());
        return;
    }

    // A missing golden fails rather than passing quietly. Otherwise a case whose
    // file was never committed would look green forever.
    let expected = image::open(&path)
        .unwrap_or_else(|err| {
            panic!(
                "could not read {}: {err}\n\
                 Regenerate with: IMAGINER_BLESS=1 cargo test -p imaginer-core --test golden",
                path.display()
            )
        })
        .to_rgba8();

    if expected == *actual {
        return;
    }

    // Written out rather than described, because the useful next step is to look at
    // the two side by side — a diff of a hundred pixel values is not readable.
    let actual_path = golden_dir().join(format!("{name}.actual.png"));
    let _ = actual.save(&actual_path);
    panic!(
        "{name} does not match its golden.\n\
         expected {} ({}x{})\n\
         actual   {} ({}x{})\n\
         Look at both. If the new one is right: \
         IMAGINER_BLESS=1 cargo test -p imaginer-core --test golden",
        path.display(),
        expected.width(),
        expected.height(),
        actual_path.display(),
        actual.width(),
        actual.height(),
    );
}

/// Every position the marker pixel occupies in `image`.
fn marker_positions(image: &RgbaImage) -> Vec<(u32, u32)> {
    image
        .enumerate_pixels()
        .filter(|(_, _, pixel)| **pixel == MARKER)
        .map(|(x, y, _)| (x, y))
        .collect()
}

/// Run one op over the fixture, check where the marker ended up, and pin the whole
/// image against its golden.
fn check(name: &str, ops: &[Op], markers: &[(u32, u32)]) {
    let mut edits = Edits::default();
    for op in ops {
        edits.push(*op);
    }
    let actual = edits.apply(&fixture()).into_owned();

    assert_eq!(
        marker_positions(&actual),
        markers,
        "{name}: the marker pixel is not where this op should have put it"
    );
    assert_matches_golden(name, &actual);
}

#[test]
fn the_fixture_marks_exactly_one_corner() {
    // Everything below reads the marker's position as an answer, so there has to be
    // exactly one of it, and it has to start in the top-left.
    assert_eq!(marker_positions(&fixture()), [(0, 0)]);
}

#[test]
fn flip_horizontal_moves_the_left_edge_to_the_right() {
    check("flip-horizontal", &[Op::FlipHorizontal], &[(WIDTH - 1, 0)]);
}

#[test]
fn flip_vertical_moves_the_top_edge_to_the_bottom() {
    check("flip-vertical", &[Op::FlipVertical], &[(0, HEIGHT - 1)]);
}

#[test]
fn rotating_clockwise_takes_the_top_left_corner_to_the_top_right() {
    // 8x6 becomes 6x8, and the corner that was at the left of the top row is now at
    // the right of it. Anticlockwise would put it at the bottom left instead, which
    // is the confusion no property test can catch.
    check("rotate-cw", &[Op::RotateCw], &[(HEIGHT - 1, 0)]);
}

#[test]
fn rotating_anticlockwise_takes_the_top_left_corner_to_the_bottom_left() {
    check("rotate-ccw", &[Op::RotateCcw], &[(0, WIDTH - 1)]);
}

#[test]
fn mirroring_sideways_keeps_the_original_and_adds_its_reflection() {
    // Two markers, because a mirror keeps the image rather than turning it over:
    // one where it started and one at the far edge of the reflection.
    check(
        "mirror-horizontal",
        &[Op::MirrorHorizontal],
        &[(0, 0), (2 * WIDTH - 1, 0)],
    );
}

#[test]
fn mirroring_downwards_puts_the_reflection_below() {
    check(
        "mirror-vertical",
        &[Op::MirrorVertical],
        &[(0, 0), (0, 2 * HEIGHT - 1)],
    );
}

#[test]
fn a_crop_keeps_the_rectangle_it_names() {
    // Starting at (1, 1), so the marker is cropped away entirely — which is itself
    // the check that the rectangle is measured from the top-left rather than from
    // some other corner.
    check(
        "crop",
        &[Op::Crop {
            x: 1,
            y: 1,
            width: 5,
            height: 4,
        }],
        &[],
    );
}

#[test]
fn an_adjustment_lands_on_exact_bytes() {
    // All three at once, so the per-pixel path runs rather than the table shortcut.
    // The marker is already white and stays white under a brightening.
    check(
        "adjust",
        &[Op::Adjust(Adjust {
            brightness: 15,
            contrast: 30,
            saturation: -40,
        })],
        &[(0, 0)],
    );
}

#[test]
fn a_whole_pipeline_composes_the_way_the_preview_shows_it() {
    // Rotate, then crop the rotated image, then colour it — the order the sidebar
    // offers and the order a save re-runs. The crop starts at column 1 of the 6x8
    // rotated image and is 5 wide, so the marker at (5, 0) is the last column it
    // keeps and lands at (4, 0); the adjustment brightens, and white has nowhere to
    // go, so it is still the marker afterwards.
    check(
        "pipeline",
        &[
            Op::RotateCw,
            Op::Crop {
                x: 1,
                y: 0,
                width: 5,
                height: 5,
            },
            Op::Adjust(Adjust {
                brightness: 10,
                contrast: 0,
                saturation: 60,
            }),
        ],
        &[(4, 0)],
    );
}
