//! Rasterises the logo and UI-icon SVGs at build time.
//!
//! The alternative — rendering SVG at runtime — would mean carrying resvg in the
//! shipping binary and paying for it during startup, which is the one thing this
//! project is not willing to spend. Doing it here keeps the SVG as the source of
//! truth (edit the artwork, rebuild, done) while the binary only ever sees a flat
//! array of pixels it can hand straight to the window manager or the GPU.

use std::path::{Path, PathBuf};

use resvg::{tiny_skia, usvg};

/// Window icon edge, in pixels. Windows asks for anything from 16px in the title bar
/// to 256px in alt-tab; 128 downsamples cleanly to all of them without the weight of
/// a full 256px buffer.
const ICON_SIZE: u32 = 128;

/// Logotype width, in pixels. Drawn at roughly half this size, so the extra pixels
/// are headroom for high-DPI displays rather than waste.
const LOGOTYPE_WIDTH: u32 = 384;

/// Edge of a rasterised UI icon, in pixels. Drawn at ~18px, so this is 2.6x
/// oversampled: enough headroom for a 200% display, and minified everywhere else,
/// which is the case the mipmapped linear filter handles well.
const UI_ICON_SIZE: u32 = 48;

fn main() {
    let assets = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("imaginer-ui has a parent directory")
        .join("assets");
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));

    let icon = render(&assets.join("imaginer_logoicon.svg"), ICON_SIZE);
    let logotype = render(&assets.join("imaginer_logotype.svg"), LOGOTYPE_WIDTH);

    std::fs::write(out_dir.join("logoicon.rgba"), &icon.rgba).expect("failed to write icon pixels");
    std::fs::write(out_dir.join("logotype.rgba"), &logotype.rgba)
        .expect("failed to write logotype pixels");

    // Emitted rather than hard-coded in both places, so the constants above stay the
    // only definition of the sizes.
    std::fs::write(
        out_dir.join("logo_dimensions.rs"),
        format!(
            "pub const ICON_SIZE: u32 = {};\n\
             pub const LOGOTYPE_SIZE: [usize; 2] = [{}, {}];\n",
            icon.width, logotype.width, logotype.height
        ),
    )
    .expect("failed to write logo dimensions");

    rasterise_ui_icons(&assets.join("icons"), &out_dir);
}

/// Rasterise every icon in `dir` into one packed blob of alpha masks, plus the
/// generated enum that indexes it.
///
/// Only the alpha channel is kept. The icons are monochrome strokes, so the three
/// colour channels carry no information the runtime needs — it tints them from the
/// widget's own foreground colour instead, which is also what makes hover, disabled
/// and active states free rather than three more rasters. At 48px that is 2.25KB an
/// icon rather than 9KB.
fn rasterise_ui_icons(dir: &Path, out_dir: &Path) {
    // Directory-level, so adding or removing an icon rebuilds. `render` adds a
    // per-file watch on top, which is what catches edits to the artwork itself.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut icons: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()))
        .map(|entry| {
            entry
                .expect("failed to read an icon directory entry")
                .path()
        })
        .filter(|path| path.extension().is_some_and(|ext| ext == "svg"))
        .collect();
    // read_dir order is filesystem-defined; sorting is what keeps the generated
    // enum's variant order — and therefore its discriminants — stable across builds.
    icons.sort();

    let mut masks = Vec::with_capacity(icons.len() * (UI_ICON_SIZE * UI_ICON_SIZE) as usize);
    let mut variants = String::new();

    for path in &icons {
        let raster = render(path, UI_ICON_SIZE);
        assert_eq!(
            raster.height,
            UI_ICON_SIZE,
            "{} is not square; the runtime assumes every icon mask is {UI_ICON_SIZE}x{UI_ICON_SIZE}",
            path.display()
        );
        masks.extend(raster.rgba.chunks_exact(4).map(|pixel| pixel[3]));

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("icon name is not valid UTF-8: {}", path.display()));
        variants.push_str(&format!(
            "    /// `{stem}.svg`\n    {},\n",
            camel_case(stem)
        ));
    }

    std::fs::write(out_dir.join("icons.alpha"), &masks).expect("failed to write icon masks");
    std::fs::write(
        out_dir.join("icons.rs"),
        format!(
            "// @generated by build.rs — add or edit files in assets/icons/ instead.\n\
             \n\
             /// Edge of every rasterised icon mask, in pixels.\n\
             pub const ICON_PX: usize = {UI_ICON_SIZE};\n\
             \n\
             /// Number of icons in the packed mask blob.\n\
             pub const ICON_COUNT: usize = {};\n\
             \n\
             /// One variant per `assets/icons/*.svg`, in sorted filename order — the\n\
             /// discriminant doubles as the icon's slot in the blob.\n\
             //\n\
             // The whole set is generated whether or not the UI reaches for it yet:\n\
             // the artwork is a set, and an icon nothing draws costs 2.25KB in the\n\
             // binary and nothing at all at runtime, since uploads are lazy.\n\
             #[allow(dead_code)]\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             pub enum Icon {{\n{variants}}}\n",
            icons.len(),
        ),
    )
    .expect("failed to write icon table");
}

/// `flip-horizontal-2` -> `FlipHorizontal2`.
fn camel_case(stem: &str) -> String {
    stem.split('-')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

struct Raster {
    width: u32,
    height: u32,
    /// Straight (non-premultiplied) RGBA, which is what both `egui::IconData` and
    /// `ColorImage::from_rgba_unmultiplied` expect.
    rgba: Vec<u8>,
}

fn render(svg_path: &Path, target_width: u32) -> Raster {
    println!("cargo:rerun-if-changed={}", svg_path.display());

    let svg = std::fs::read(svg_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", svg_path.display()));
    let tree = usvg::Tree::from_data(&svg, &usvg::Options::default())
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", svg_path.display()));

    // Scale uniformly from the SVG's own size so the artwork keeps its aspect ratio
    // whatever the source viewBox happens to be.
    let scale = target_width as f32 / tree.size().width();
    let height = (tree.size().height() * scale).round().max(1.0) as u32;

    let mut pixmap = tiny_skia::Pixmap::new(target_width, height)
        .unwrap_or_else(|| panic!("invalid raster size {target_width}x{height}"));
    resvg::render(
        &tree,
        tiny_skia::Transform::from_scale(scale, scale),
        &mut pixmap.as_mut(),
    );

    // tiny-skia composites in premultiplied alpha; undo that here rather than in the
    // app, so the runtime never has to know how these pixels were produced.
    let mut rgba = Vec::with_capacity(pixmap.pixels().len() * 4);
    for pixel in pixmap.pixels() {
        let demultiplied = pixel.demultiply();
        rgba.extend_from_slice(&[
            demultiplied.red(),
            demultiplied.green(),
            demultiplied.blue(),
            demultiplied.alpha(),
        ]);
    }

    Raster {
        width: target_width,
        height,
        rgba,
    }
}
